"""esquema inicial de la lista de espera

Revision ID: 9d4e4a0b0ff3
Revises: 
Create Date: 2026-09-18 20:11:10.829918
"""
from alembic import op
import sqlalchemy as sa


revision = '9d4e4a0b0ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('expected_turn_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('held_by_entry_id', sa.String(length=36), nullable=True),
    sa.Column('held_at', sa.DateTime(), nullable=True),
    sa.Column('occupied_since', sa.DateTime(), nullable=True),
    sa.Column('auto_release_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('held_by_entry_id', name='uq_una_mesa_por_entrada'),
    sa.UniqueConstraint('venue_id', 'label', name='uq_table_label_por_local')
    )
    op.create_table('waitlist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('guest_name', sa.String(length=80), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('on_the_way_at', sa.DateTime(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=8), nullable=True),
    sa.Column('assigned_table_id', sa.String(length=36), nullable=True),
    sa.Column('table_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('seated_over_capacity', sa.Boolean(), nullable=False),
    sa.Column('quoted_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    op.create_index('ix_cola_del_dia', 'waitlist_entries', ['venue_id', 'service_date', 'status', 'joined_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cola_del_dia', table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_table('tables')
    op.drop_table('venues')
    # ### end Alembic commands ###
